const TZ_MAP: Record<string, string> = {
  'Europe/Amsterdam': 'NL',
  'Europe/Berlin': 'DE',
  'Europe/Vienna': 'AT',
  'Europe/Zurich': 'CH',
  'Europe/Brussels': 'BE',
  'Europe/Paris': 'FR',
  'Europe/Luxembourg': 'LU',
  'Europe/Madrid': 'ES',
  'Europe/Rome': 'IT',
  'Europe/Lisbon': 'PT',
  'Europe/Athens': 'GR',
  'Europe/Zagreb': 'HR',
  'Europe/Ljubljana': 'SI',
  'Europe/London': 'GB',
  'Europe/Dublin': 'IE',
  'Europe/Stockholm': 'SE',
  'Europe/Oslo': 'NO',
  'Europe/Copenhagen': 'DK',
  'Europe/Helsinki': 'FI',
  'Europe/Warsaw': 'PL',
  'Europe/Prague': 'CZ',
  'Europe/Bratislava': 'SK',
  'Europe/Budapest': 'HU',
  'Europe/Bucharest': 'RO',
  'Europe/Sofia': 'BG',
  'Europe/Istanbul': 'TR',
  'Europe/Kiev': 'UA',
  'Europe/Moscow': 'RU',
  'America/New_York': 'US',
  'America/Chicago': 'US',
  'America/Denver': 'US',
  'America/Los_Angeles': 'US',
  'America/Phoenix': 'US',
  'America/Anchorage': 'US',
  'Pacific/Honolulu': 'US',
  'America/Toronto': 'CA',
  'America/Vancouver': 'CA',
  'America/Mexico_City': 'MX',
  'America/Sao_Paulo': 'BR',
  'America/Argentina/Buenos_Aires': 'AR',
  'America/Bogota': 'CO',
  'America/Santiago': 'CL',
  'America/Lima': 'PE',
  'America/Caracas': 'VE',
  'America/Montevideo': 'UY',
  'America/Asuncion': 'PY',
  'America/Paramaribo': 'SR',
  'America/Curacao': 'CW',
  'America/Aruba': 'AW',
  'Asia/Tokyo': 'JP',
  'Asia/Shanghai': 'CN',
  'Asia/Seoul': 'KR',
  'Asia/Kolkata': 'IN',
  'Asia/Jakarta': 'ID',
  'Asia/Bangkok': 'TH',
  'Asia/Ho_Chi_Minh': 'VN',
  'Asia/Manila': 'PH',
  'Asia/Kuala_Lumpur': 'MY',
  'Asia/Singapore': 'SG',
  'Asia/Riyadh': 'SA',
  'Asia/Dubai': 'AE',
  'Asia/Jerusalem': 'IL',
  'Australia/Sydney': 'AU',
  'Pacific/Auckland': 'NZ',
  'Africa/Johannesburg': 'ZA',
  'Africa/Lagos': 'NG',
  'Africa/Nairobi': 'KE',
  'Africa/Cairo': 'EG',
  'Africa/Casablanca': 'MA',
};

const COUNTRY_NAMES: Record<string, string> = {
  NL: 'Nederland',
  BE: 'België',
  DE: 'Deutschland',
  AT: 'Österreich',
  CH: 'Schweiz',
  FR: 'France',
  LU: 'Luxembourg',
  ES: 'España',
  IT: 'Italia',
  PT: 'Portugal',
  GR: 'Ελλάδα',
  HR: 'Hrvatska',
  SI: 'Slovenija',
  GB: 'United Kingdom',
  IE: 'Ireland',
  SE: 'Sverige',
  NO: 'Norge',
  DK: 'Danmark',
  FI: 'Suomi',
  PL: 'Polska',
  CZ: 'Česko',
  SK: 'Slovensko',
  HU: 'Magyarország',
  RO: 'România',
  BG: 'България',
  TR: 'Türkiye',
  US: 'United States',
  CA: 'Canada',
  MX: 'México',
  BR: 'Brasil',
  AR: 'Argentina',
  CO: 'Colombia',
  CL: 'Chile',
  PE: 'Perú',
  VE: 'Venezuela',
  EC: 'Ecuador',
  UY: 'Uruguay',
  PY: 'Paraguay',
  BO: 'Bolivia',
  CR: 'Costa Rica',
  PA: 'Panamá',
  DO: 'República Dominicana',
  GT: 'Guatemala',
  HN: 'Honduras',
  SV: 'El Salvador',
  NI: 'Nicaragua',
  CU: 'Cuba',
  PR: 'Puerto Rico',
  JM: 'Jamaica',
  TT: 'Trinidad and Tobago',
  SR: 'Suriname',
  GY: 'Guyana',
  BZ: 'Belize',
  HT: 'Haïti',
  BB: 'Barbados',
  AW: 'Aruba',
  CW: 'Curaçao',
  BQ: 'Bonaire',
  SX: 'Sint Maarten',
  JP: '日本',
  CN: '中国',
  KR: '한국',
  IN: 'India',
  ID: 'Indonesia',
  TH: 'ประเทศไทย',
  VN: 'Việt Nam',
  PH: 'Pilipinas',
  MY: 'Malaysia',
  SG: 'Singapore',
  KH: 'Cambodia',
  LA: 'Laos',
  MM: 'Myanmar',
  BD: 'Bangladesh',
  LK: 'Sri Lanka',
  NP: 'Nepal',
  PK: 'Pakistan',
  SA: 'السعودية',
  AE: 'الإمارات',
  IL: 'ישראל',
  QA: 'قطر',
  KW: 'الكويت',
  BH: 'البحرين',
  OM: 'عُمان',
  JO: 'الأردن',
  LB: 'لبنان',
  IQ: 'العراق',
  AU: 'Australia',
  NZ: 'New Zealand',
  ZA: 'South Africa',
  NG: 'Nigeria',
  KE: 'Kenya',
  GH: 'Ghana',
  EG: 'مصر',
  MA: 'المغرب',
  TN: 'تونس',
  GM: 'Gambia',
  SN: 'Sénégal',
  CI: "Côte d'Ivoire",
  CM: 'Cameroun',
  TZ: 'Tanzania',
  UG: 'Uganda',
  ET: 'Ethiopia',
  RW: 'Rwanda',
  MZ: 'Moçambique',
  AO: 'Angola',
  CD: 'Congo-Kinshasa',
  CG: 'Congo-Brazzaville',
  ML: 'Mali',
  BF: 'Burkina Faso',
  NE: 'Niger',
  TD: 'Tchad',
  MG: 'Madagascar',
  MW: 'Malawi',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  BW: 'Botswana',
  NA: 'Namibia',
  SL: 'Sierra Leone',
  LR: 'Liberia',
  GN: 'Guinée',
  BJ: 'Bénin',
  TG: 'Togo',
  MR: 'Mauritanie',
  SO: 'Soomaaliya',
  SD: 'Sudan',
  SS: 'South Sudan',
  ER: 'Eritrea',
  DJ: 'Djibouti',
  LY: 'Libya',
  DZ: 'الجزائر',
  MU: 'Mauritius',
  SC: 'Seychelles',
  CV: 'Cabo Verde',
  RU: 'Россия',
  UA: 'Україна',
};

export function initNavCountryLabel(): void {
  const el = document.getElementById('nav-country');
  if (!el) return;

  const match = document.cookie.match(/(?:^|;\s*)pagayo_country=([A-Z]{2})/);
  let code = match?.[1] ?? null;

  if (!code) {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
    code = TZ_MAP[tz] ?? null;
  }

  if (!code) return;

  const name = COUNTRY_NAMES[code];
  if (name) el.textContent = name;
}
